board_game:
  name: gomoku
  m: 15
  n: 15
  k: 5
  cell_size: 30
  fps: 60
  menu_font_size: 30
  button_font_size: 25
  symbol_font_size: 30
bot:
  algorithm: mcts
  config:
    thinking_time: 1.0  # in seconds
    processes: 8  # number of processes
    policy: simple
    exploration_const: 1.4142135623730951