board_game:
  name: tic-tac-toe
  m: 3
  n: 3
  k: 3
  cell_size: 90
  fps: 60
  menu_font_size: 30
  button_font_size: 15
  symbol_font_size: 90
bot:
  algorithm: mcts
  config:
    thinking_time: 1.0  # in seconds
    processes: 8  # number of processes
    policy: simple
    exploration_const: 1.4142135623730951